// Generated by scripts/generate-app-contracts.mjs. Do not edit.

export const APP_CONTRACT_REVISION = "sha256:2b033df33d968a6f7ca323d0a9c909d07b448dc3bdbfd5baf3beae1230fe1661" as const;
export const APP_CONTRACTS = [
  {
    "app_id": "home",
    "title": "Home",
    "icon_key": "home",
    "execution_context_kind": "personal",
    "resource_scope": "personal",
    "route_base": "/apps/home",
    "entry_route_id": "home.root",
    "launcher": {
      "placement": "fixed",
      "pinned_by_default": false
    },
    "routes": [
      {
        "route_id": "home.root",
        "suffix": "",
        "chrome": "containedSurface"
      }
    ],
    "management": {
      "summary": "Personal launcher and activity overview",
      "capabilities": [
        "launcher",
        "navigation"
      ],
      "source_paths": [
        "apps/web/src/app-modules/home"
      ],
      "release_unit": "miy-app"
    },
    "title_translations": {
      "ko-KR": "홈",
      "en-US": "Home"
    }
  },
  {
    "app_id": "agent-terminal",
    "title": "Codex Terminal",
    "icon_key": "square-terminal",
    "execution_context_kind": "personal",
    "resource_scope": "personal",
    "route_base": "/apps/agent-terminal",
    "entry_route_id": "agent-terminal.root",
    "launcher": {
      "placement": "personal_tools",
      "pinned_by_default": false
    },
    "required_system_roles": [
      "platform_admin"
    ],
    "feature_flag": "agent_terminal_enabled",
    "routes": [
      {
        "route_id": "agent-terminal.root",
        "suffix": "",
        "chrome": "fullSurface"
      }
    ],
    "management": {
      "summary": "Subscription authenticated coding terminal",
      "capabilities": [
        "coding",
        "terminal"
      ],
      "source_paths": [
        "apps/web/src/app-modules/agent-terminal",
        "apps/api/src/miy_api/domains/agent_terminal"
      ],
      "release_unit": "miy-app"
    },
    "title_translations": {
      "ko-KR": "Codex 터미널",
      "en-US": "Codex Terminal"
    }
  },
  {
    "app_id": "codex-console",
    "title": "MIY Workbench",
    "icon_key": "code-xml",
    "execution_context_kind": "personal",
    "resource_scope": "personal",
    "route_base": "/apps/codex-console",
    "entry_route_id": "codex-console.root",
    "launcher": {
      "placement": "personal_tools",
      "pinned_by_default": false,
      "url_setting": "codex_console_launch_url"
    },
    "required_system_roles": [
      "platform_admin"
    ],
    "feature_flag": "codex_console_enabled",
    "routes": [
      {
        "route_id": "codex-console.root",
        "suffix": "",
        "chrome": "containedSurface"
      }
    ],
    "management": {
      "summary": "App development, maintenance and platform operations",
      "capabilities": [
        "studio",
        "delivery",
        "maintenance"
      ],
      "source_paths": [
        "apps/codex-console-web/src",
        "apps/codex-console-api/src/codex_console"
      ],
      "release_unit": "miy-workbench"
    },
    "title_translations": {
      "ko-KR": "MIY Workbench",
      "en-US": "MIY Workbench"
    }
  },
  {
    "app_id": "chatbot",
    "title": "AI Assistant",
    "icon_key": "message-square",
    "execution_context_kind": "personal",
    "resource_scope": "personal",
    "route_base": "/apps/chatbot",
    "entry_route_id": "chatbot.root",
    "launcher": {
      "placement": "category",
      "pinned_by_default": false
    },
    "routes": [
      {
        "route_id": "chatbot.root",
        "suffix": "",
        "chrome": "containedSurface"
      }
    ],
    "management": {
      "summary": "AI conversations, research and generated artifacts",
      "capabilities": [
        "ai",
        "conversation",
        "research"
      ],
      "source_paths": [
        "packages/platform-web/src/chatbot",
        "apps/web/src/app-modules/chatbot",
        "apps/api/src/miy_api/domains/conversations",
        "apps/api/src/miy_api/domains/ai"
      ],
      "release_unit": "miy-app"
    },
    "title_translations": {
      "ko-KR": "AI 어시스턴트 챗봇",
      "en-US": "AI Assistant Chatbot"
    }
  },
  {
    "app_id": "pms",
    "title": "PMS",
    "icon_key": "folder-kanban",
    "execution_context_kind": "company",
    "resource_scope": "company",
    "route_base": "/apps/pms",
    "entry_route_id": "pms.root",
    "launcher": {
      "placement": "category",
      "pinned_by_default": true
    },
    "routes": [
      {
        "route_id": "pms.root",
        "suffix": "",
        "chrome": "containedSurface"
      },
      {
        "route_id": "pms.assigned",
        "suffix": "/assigned",
        "chrome": "containedSurface"
      },
      {
        "route_id": "pms.today",
        "suffix": "/today",
        "chrome": "containedSurface"
      },
      {
        "route_id": "pms.list",
        "suffix": "/lists/:taskListId",
        "chrome": "containedSurface"
      },
      {
        "route_id": "pms.space",
        "suffix": "/spaces/:spaceId",
        "chrome": "containedSurface"
      },
      {
        "route_id": "pms.space-docs",
        "suffix": "/spaces/:spaceId/docs",
        "chrome": "containedSurface"
      },
      {
        "route_id": "pms.space-doc",
        "suffix": "/spaces/:spaceId/docs/:docId",
        "chrome": "containedSurface"
      },
      {
        "route_id": "pms.space-whiteboards",
        "suffix": "/spaces/:spaceId/whiteboards",
        "chrome": "containedSurface"
      },
      {
        "route_id": "pms.space-whiteboard",
        "suffix": "/spaces/:spaceId/whiteboards/:whiteboardId",
        "chrome": "containedSurface"
      }
    ],
    "management": {
      "summary": "Projects, tasks and team collaboration",
      "capabilities": [
        "projects",
        "tasks",
        "workflow"
      ],
      "source_paths": [
        "packages/official-suite-web/src/pms",
        "packages/official-suite-web/public/help/pms/user-guide.html",
        "packages/official-suite-web/vite/fixed-assets.mts",
        "apps/web/src/app-modules/pms",
        "apps/api/src/miy_api/domains/pms"
      ],
      "release_unit": "miy-app"
    },
    "title_translations": {
      "ko-KR": "PMS",
      "en-US": "PMS"
    }
  },
  {
    "app_id": "docs",
    "title": "Docs",
    "icon_key": "files",
    "execution_context_kind": "personal",
    "resource_scope": "hybrid",
    "route_base": "/apps/docs",
    "entry_route_id": "docs.root",
    "launcher": {
      "placement": "category",
      "pinned_by_default": true
    },
    "routes": [
      {
        "route_id": "docs.root",
        "suffix": "",
        "chrome": "standard"
      },
      {
        "route_id": "docs.document",
        "suffix": "/documents/:docId",
        "chrome": "standard"
      },
      {
        "route_id": "docs.document-html",
        "suffix": "/documents/:docId/html/:pageId",
        "chrome": "containedSurface"
      },
      {
        "route_id": "docs.shared",
        "suffix": "/shared/:shareToken",
        "chrome": "shared"
      },
      {
        "route_id": "docs.shared-html",
        "suffix": "/shared/:shareToken/html/:pageId",
        "chrome": "shared"
      }
    ],
    "management": {
      "summary": "Collaborative document authoring and sharing",
      "capabilities": [
        "documents",
        "collaboration"
      ],
      "source_paths": [
        "packages/official-suite-web/src/docs",
        "apps/web/src/app-modules/docs",
        "apps/api/src/miy_api/domains/docs"
      ],
      "release_unit": "miy-app"
    },
    "title_translations": {
      "ko-KR": "문서",
      "en-US": "Docs"
    }
  },
  {
    "app_id": "files",
    "title": "Files",
    "icon_key": "folder",
    "execution_context_kind": "personal",
    "resource_scope": "hybrid",
    "route_base": "/apps/files",
    "entry_route_id": "files.root",
    "launcher": {
      "placement": "category",
      "pinned_by_default": false
    },
    "routes": [
      {
        "route_id": "files.root",
        "suffix": "",
        "chrome": "standard"
      },
      {
        "route_id": "files.chat",
        "suffix": "/chat",
        "chrome": "standard"
      }
    ],
    "management": {
      "summary": "File upload, storage and sharing",
      "capabilities": [
        "files",
        "storage"
      ],
      "source_paths": [
        "packages/official-suite-web/src/files",
        "apps/web/src/app-modules/files",
        "apps/api/src/miy_api/domains/files"
      ],
      "release_unit": "miy-app"
    },
    "title_translations": {
      "ko-KR": "파일",
      "en-US": "Files"
    }
  },
  {
    "app_id": "mail",
    "title": "Mail",
    "icon_key": "mail",
    "execution_context_kind": "personal",
    "resource_scope": "personal",
    "route_base": "/apps/mail",
    "entry_route_id": "mail.root",
    "launcher": {
      "placement": "personal_tools",
      "pinned_by_default": false
    },
    "routes": [
      {
        "route_id": "mail.root",
        "suffix": "",
        "chrome": "standard"
      }
    ],
    "management": {
      "summary": "Personal mailbox and correspondence",
      "capabilities": [
        "mail",
        "communication"
      ],
      "source_paths": [
        "packages/official-suite-web/src/mail",
        "apps/web/src/app-modules/mail",
        "apps/api/src/miy_api/domains/mail"
      ],
      "release_unit": "miy-app"
    },
    "title_translations": {
      "ko-KR": "메일",
      "en-US": "Mail"
    }
  },
  {
    "app_id": "community",
    "title": "Community",
    "icon_key": "message-square",
    "execution_context_kind": "company",
    "resource_scope": "company",
    "route_base": "/apps/community",
    "entry_route_id": "community.root",
    "launcher": {
      "placement": "category",
      "pinned_by_default": false
    },
    "routes": [
      {
        "route_id": "community.root",
        "suffix": "",
        "chrome": "standard"
      },
      {
        "route_id": "community.post",
        "suffix": "/posts/:postId",
        "chrome": "standard"
      }
    ],
    "management": {
      "summary": "Company discussions and suggestions",
      "capabilities": [
        "community",
        "discussion"
      ],
      "source_paths": [
        "packages/official-suite-web/src/community",
        "apps/web/src/app-modules/community",
        "apps/api/src/miy_api/domains/community"
      ],
      "release_unit": "miy-app"
    },
    "title_translations": {
      "ko-KR": "커뮤니티",
      "en-US": "Community"
    }
  },
  {
    "app_id": "whiteboard",
    "title": "Whiteboard",
    "icon_key": "pencil-ruler",
    "execution_context_kind": "personal",
    "resource_scope": "hybrid",
    "route_base": "/apps/whiteboard",
    "entry_route_id": "whiteboard.root",
    "launcher": {
      "placement": "category",
      "pinned_by_default": true
    },
    "routes": [
      {
        "route_id": "whiteboard.root",
        "suffix": "",
        "chrome": "standard"
      },
      {
        "route_id": "whiteboard.board",
        "suffix": "/boards/:whiteboardId",
        "chrome": "containedSurface"
      },
      {
        "route_id": "whiteboard.shared",
        "suffix": "/shared/:shareToken",
        "chrome": "shared"
      }
    ],
    "management": {
      "summary": "Collaborative visual whiteboards",
      "capabilities": [
        "whiteboard",
        "collaboration"
      ],
      "source_paths": [
        "packages/official-suite-web/src/whiteboard",
        "apps/web/src/app-modules/whiteboard",
        "apps/api/src/miy_api/domains/whiteboard"
      ],
      "release_unit": "miy-app"
    },
    "title_translations": {
      "ko-KR": "화이트보드",
      "en-US": "Whiteboard"
    }
  },
  {
    "app_id": "diagrams",
    "title": "Diagrams",
    "icon_key": "workflow",
    "execution_context_kind": "personal",
    "resource_scope": "hybrid",
    "route_base": "/apps/diagrams",
    "entry_route_id": "diagrams.root",
    "launcher": {
      "placement": "category",
      "pinned_by_default": false
    },
    "routes": [
      {
        "route_id": "diagrams.root",
        "suffix": "",
        "chrome": "standard"
      },
      {
        "route_id": "diagrams.diagram",
        "suffix": "/diagrams/:diagramId",
        "chrome": "containedSurface"
      }
    ],
    "management": {
      "summary": "Diagram editing and sharing",
      "capabilities": [
        "diagram",
        "drawing"
      ],
      "source_paths": [
        "apps/web/src/app-modules/diagrams",
        "packages/official-suite-web/src/diagrams",
        "apps/api/src/miy_api/domains/diagrams"
      ],
      "release_unit": "miy-app"
    },
    "title_translations": {
      "ko-KR": "다이어그램",
      "en-US": "Diagrams"
    }
  },
  {
    "app_id": "bento",
    "title": "Bento",
    "icon_key": "presentation",
    "execution_context_kind": "personal",
    "resource_scope": "hybrid",
    "route_base": "/apps/bento",
    "entry_route_id": "bento.root",
    "launcher": {
      "placement": "category",
      "pinned_by_default": false
    },
    "routes": [
      {
        "route_id": "bento.root",
        "suffix": "",
        "chrome": "standard"
      },
      {
        "route_id": "bento.presentation",
        "suffix": "/presentations/:documentId",
        "chrome": "containedSurface"
      }
    ],
    "management": {
      "summary": "Presentation editing and sharing",
      "capabilities": [
        "presentation",
        "slides"
      ],
      "source_paths": [
        "apps/web/src/app-modules/bento",
        "packages/official-suite-web/src/bento",
        "apps/api/src/miy_api/domains/bento"
      ],
      "release_unit": "miy-app"
    },
    "title_translations": {
      "ko-KR": "bento/slides",
      "en-US": "bento/slides"
    }
  },
  {
    "app_id": "planner",
    "title": "Planner",
    "icon_key": "calendar",
    "execution_context_kind": "personal",
    "resource_scope": "personal",
    "route_base": "/apps/planner",
    "entry_route_id": "planner.root",
    "launcher": {
      "placement": "personal_tools",
      "pinned_by_default": false
    },
    "routes": [
      {
        "route_id": "planner.root",
        "suffix": "",
        "chrome": "fullSurface"
      }
    ],
    "management": {
      "summary": "Personal plans and task scheduling",
      "capabilities": [
        "planning",
        "calendar"
      ],
      "source_paths": [
        "packages/official-suite-web/src/planner",
        "packages/official-suite-web/src/calendar",
        "apps/web/src/app-modules/planner",
        "apps/web/src/platform/calendar",
        "apps/api/src/miy_api/domains/planner",
        "apps/api/src/miy_api/domains/calendar"
      ],
      "release_unit": "miy-app"
    },
    "title_translations": {
      "ko-KR": "플래너",
      "en-US": "Planner"
    }
  },
  {
    "app_id": "meeting",
    "title": "Meeting",
    "icon_key": "users",
    "execution_context_kind": "company",
    "resource_scope": "company",
    "route_base": "/apps/meeting",
    "entry_route_id": "meeting.root",
    "launcher": {
      "placement": "category",
      "pinned_by_default": false
    },
    "routes": [
      {
        "route_id": "meeting.root",
        "suffix": "",
        "chrome": "standard"
      },
      {
        "route_id": "meeting.detail",
        "suffix": "/meetings/:meetingId",
        "chrome": "standard"
      }
    ],
    "management": {
      "summary": "Meetings, agendas and shared notes",
      "capabilities": [
        "meeting",
        "minutes"
      ],
      "source_paths": [
        "packages/official-suite-web/src/meeting",
        "apps/web/src/app-modules/meeting",
        "apps/api/src/miy_api/domains/meeting"
      ],
      "release_unit": "miy-app"
    },
    "title_translations": {
      "ko-KR": "회의",
      "en-US": "Meeting"
    }
  },
  {
    "app_id": "video-chat",
    "title": "Video Chat",
    "icon_key": "video",
    "execution_context_kind": "company",
    "resource_scope": "company",
    "route_base": "/apps/video-chat",
    "entry_route_id": "video-chat.root",
    "launcher": {
      "placement": "category",
      "pinned_by_default": false
    },
    "routes": [
      {
        "route_id": "video-chat.root",
        "suffix": "",
        "chrome": "standard"
      },
      {
        "route_id": "video-chat.session",
        "suffix": "/sessions/:sessionId",
        "chrome": "containedSurface"
      }
    ],
    "management": {
      "summary": "Real-time video meetings",
      "capabilities": [
        "video",
        "communication"
      ],
      "source_paths": [
        "packages/official-suite-web/src/video-chat",
        "apps/web/src/app-modules/video-chat",
        "apps/api/src/miy_api/domains/video_chat"
      ],
      "release_unit": "miy-app"
    },
    "title_translations": {
      "ko-KR": "화상채팅",
      "en-US": "Video Chat"
    }
  },
  {
    "app_id": "recording",
    "title": "Recording",
    "icon_key": "mic",
    "execution_context_kind": "personal",
    "resource_scope": "personal",
    "route_base": "/apps/recording",
    "entry_route_id": "recording.root",
    "launcher": {
      "placement": "category",
      "pinned_by_default": false
    },
    "routes": [
      {
        "route_id": "recording.root",
        "suffix": "",
        "chrome": "standard"
      },
      {
        "route_id": "recording.detail",
        "suffix": "/recordings/:recordingId",
        "chrome": "standard"
      }
    ],
    "management": {
      "summary": "Recordings and transcription",
      "capabilities": [
        "recording",
        "transcription"
      ],
      "source_paths": [
        "packages/official-suite-web/src/recording",
        "packages/official-suite-web/public/recording-sync-sw.js",
        "packages/official-suite-web/vite/recording-sync-asset.mts",
        "apps/web/src/app-modules/recording",
        "apps/api/src/miy_api/domains/recording"
      ],
      "release_unit": "miy-app"
    },
    "title_translations": {
      "ko-KR": "녹음",
      "en-US": "Recording"
    }
  },
  {
    "app_id": "retrieval-search",
    "title": "Retrieval Search",
    "icon_key": "search",
    "execution_context_kind": "personal",
    "resource_scope": "hybrid",
    "route_base": "/apps/retrieval-search",
    "entry_route_id": "retrieval-search.root",
    "launcher": {
      "placement": "category",
      "pinned_by_default": false
    },
    "routes": [
      {
        "route_id": "retrieval-search.root",
        "suffix": "",
        "chrome": "standard"
      }
    ],
    "management": {
      "summary": "Search over authorized indexed sources",
      "capabilities": [
        "search",
        "retrieval"
      ],
      "source_paths": [
        "apps/web/src/app-modules/retrieval-search",
        "apps/api/src/miy_api/domains/retrieval"
      ],
      "release_unit": "miy-app"
    },
    "title_translations": {
      "ko-KR": "Retrieval 진단 검색",
      "en-US": "Retrieval Diagnostics"
    }
  },
  {
    "app_id": "tetris",
    "title": "Tetris",
    "icon_key": "boxes",
    "execution_context_kind": "personal",
    "resource_scope": "personal",
    "route_base": "/apps/tetris",
    "entry_route_id": "tetris.root",
    "launcher": {
      "placement": "personal_tools",
      "pinned_by_default": false
    },
    "routes": [
      {
        "route_id": "tetris.root",
        "suffix": "",
        "chrome": "containedSurface"
      }
    ],
    "management": {
      "summary": "Personal Tetris game",
      "capabilities": [
        "game"
      ],
      "source_paths": [
        "apps/web/src/app-modules/tetris",
        "apps/api/src/miy_api/domains/tetris"
      ],
      "release_unit": "miy-app"
    },
    "title_translations": {
      "ko-KR": "테트리스",
      "en-US": "Tetris"
    }
  }
] as const;

export type AppContract = (typeof APP_CONTRACTS)[number];
export type AppId = AppContract['app_id'];
export const OFFICIAL_APP_IDS = ["pms","docs","files","mail","community","whiteboard","diagrams","bento","planner","meeting","video-chat","recording"] as const satisfies readonly AppId[];
export type AppRouteContract = AppContract['routes'][number];
export type AppRouteId = AppRouteContract['route_id'];
export type AppExecutionContextKind = AppContract['execution_context_kind'];
export type AppResourceScope = AppContract['resource_scope'];

export const APP_CONTRACT_BY_ID = new Map<AppId, AppContract>(
  APP_CONTRACTS.map((app) => [app.app_id, app]),
);

export const APP_ROUTE_BY_ID = new Map<AppRouteId, AppRouteContract & { app_id: AppId; route_base: string }>(
  APP_CONTRACTS.flatMap((app) =>
    app.routes.map((route) => [route.route_id, { ...route, app_id: app.app_id, route_base: app.route_base }] as const),
  ),
);
