import { getAppRoutePattern } from '@miy/contracts/app-routes';
import {
  Calendar,
  CheckCircle2,
  FolderKanban,
  Inbox,
  User,
} from 'lucide-react';

import type { AppModuleManifest } from '@miy/core-web/navigation-types';

export const pmsManifest: AppModuleManifest = {
  appBarItem: { id: 'pms', title: 'PMS', icon: FolderKanban },
  contract: {
    owner: 'pms-platform',
    permissions: [],
    apiDomain: 'pms',
    aiCapabilities: [
      'pms.search_tasks',
      'pms.get_task',
      'pms.list_spaces',
      'pms.list_task_lists',
      'pms.get_task_list_options',
      'pms.create_task',
      'pms.update_task',
      'pms.add_comment',
      'pms.delete_task',
    ],
    writeAuditActions: [
      'pms.create_task',
      'pms.update_task',
      'pms.add_comment',
      'pms.delete_task',
    ],
    appLocalTests: [
      'packages/official-suite-web/src/pms/api/pms-api.spec.ts',
      'packages/official-suite-web/src/pms/api/pms-filters.spec.ts',
      'packages/official-suite-web/src/pms/api/pms-permissions.spec.ts',
      'packages/official-suite-web/src/pms/api/pms-sidebar-reorder.spec.ts',
      'packages/official-suite-web/src/pms/api/pms-task-detail-scope.spec.ts',
      'packages/official-suite-web/src/pms/api/pms-task-lists.spec.ts',
      'packages/official-suite-web/src/pms/api/pms-task-reorder.spec.ts',
      'packages/official-suite-web/src/pms/views/task-picker-model.spec.ts',
      'packages/official-suite-web/src/pms/views/TaskPickerModal.spec.tsx',
      'packages/official-suite-web/src/pms/views/TaskPickerModal.locale.spec.tsx',
      'packages/official-suite-web/src/pms/views/pms-view-route.spec.ts',
      'packages/official-suite-web/src/pms/sidebar/PmsSidebarSpaces.spec.tsx',
      'packages/official-suite-web/src/pms/sidebar/SortableListLink.spec.tsx',
      'packages/official-suite-web/src/pms/sidebar/pms-sidebar-config-model.spec.ts',
      'packages/official-suite-web/src/pms/sidebar/space-order-editor-model.spec.ts',
      'packages/official-suite-web/src/pms/sidebar/space-order-persistence.spec.ts',
      'packages/official-suite-web/src/pms/sidebar/space-tree-model.spec.ts',
      'packages/official-suite-web/src/pms/views/CalendarView.spec.tsx',
      'packages/official-suite-web/src/pms/views/FilterBar.spec.tsx',
      'packages/official-suite-web/src/pms/views/FloatingPmsWidget.spec.tsx',
      'packages/official-suite-web/src/pms/views/GanttView.spec.tsx',
      'packages/official-suite-web/src/pms/views/ListView.spec.tsx',
      'packages/official-suite-web/src/pms/views/NewTaskModal.spec.tsx',
      'packages/official-suite-web/src/pms/views/SpaceGroupBindings.spec.tsx',
      'packages/official-suite-web/src/pms/views/SpaceMembersModal.spec.tsx',
      'packages/official-suite-web/src/pms/views/SpaceTasksView.spec.tsx',
      'packages/official-suite-web/src/pms/views/TableView.spec.tsx',
      'packages/official-suite-web/src/pms/views/TaskDetailActivityPanel.spec.tsx',
      'packages/official-suite-web/src/pms/views/TodayOverdueView.spec.ts',
      'packages/official-suite-web/src/pms/views/bulk-action-bar-model.spec.ts',
      'packages/official-suite-web/src/pms/views/calendar-view-model.spec.ts',
      'packages/official-suite-web/src/pms/views/filter-bar-model.spec.ts',
      'packages/official-suite-web/src/pms/views/gantt-view-model.spec.ts',
      'packages/official-suite-web/src/pms/views/list-view-editing-model.spec.ts',
      'packages/official-suite-web/src/pms/views/list-view-grouping-model.spec.ts',
      'packages/official-suite-web/src/pms/views/new-task-modal-model.spec.ts',
      'packages/official-suite-web/src/pms/views/pms-constants.spec.ts',
      'packages/official-suite-web/src/pms/views/pms-create-modal-model.spec.ts',
      'packages/official-suite-web/src/pms/views/pms-events.spec.ts',
      'packages/official-suite-web/src/pms/views/pms-task-context.spec.ts',
      'packages/official-suite-web/src/pms/views/pms-task-hierarchy.spec.ts',
      'packages/official-suite-web/src/pms/views/pms-task-list-catalog-model.spec.ts',
      'packages/official-suite-web/src/pms/views/pms-task-selection-workflow.spec.ts',
      'packages/official-suite-web/src/pms/views/pms-view-scoped-state-model.spec.ts',
      'packages/official-suite-web/src/pms/views/space-members-modal-model.spec.ts',
      'packages/official-suite-web/src/pms/views/space-overview-model.spec.ts',
      'packages/official-suite-web/src/pms/views/space-scoped-redirects.spec.ts',
      'packages/official-suite-web/src/pms/views/task-detail-editing-model.spec.ts',
      'packages/official-suite-web/src/pms/views/task-list-members-model.spec.ts',
      'packages/official-suite-web/src/pms/views/task-list-presentation-model.spec.ts',
      'packages/official-suite-web/src/pms/views/task-list-workflow-settings-model.spec.ts',
      'packages/official-suite-web/src/pms/views/today-overdue-model.spec.ts',
      'packages/official-suite-web/src/pms/views/usePmsTaskListGroupPreference.spec.ts',
      'packages/official-suite-web/src/pms/views/useTaskDetailAttachments.spec.ts',
      'packages/official-suite-web/src/pms/views/useTaskDetailChecklist.spec.ts',
      'packages/official-suite-web/src/pms/views/useTaskDetailComments.spec.ts',
      'packages/official-suite-web/src/pms/views/useTaskDetailIssueEditing.spec.ts',
      'packages/official-suite-web/src/pms/views/useTaskDetailResources.spec.ts',
      'packages/official-suite-web/src/pms/views/useTaskDetailSubtasks.spec.ts',
      'packages/official-suite-web/src/pms/views/useTaskListLabelsController.spec.ts',
      'packages/official-suite-web/src/pms/views/useTaskListMembersController.spec.ts',
      'packages/official-suite-web/src/pms/views/useTaskListWorkflowStatusesController.spec.ts',
      'apps/web/src/app-modules/pms/help-guide.spec.ts',
      'apps/web/src/app-modules/pms/pms-source-compatibility.spec.tsx',
      'apps/web/src/app-modules/pms/views/useTaskDetailLinkedDocs.spec.ts',
      'apps/web/src/app-shell-navigation-model.spec.ts',
      'apps/web/src/app-modules/pms/ownership.spec.tsx',
      'apps/api/tests/test_pms_issues.py',
    ],
  },
  defaultActiveNavItemId: 'pms-inbox',
  navItems: [
    {
      id: 'pms-inbox',
      title: 'pms-inbox',
      icon: Inbox,
      category: 'Personal',
      appId: 'pms',
    },
    {
      id: 'pms-tasks',
      title: 'pms-tasks',
      icon: CheckCircle2,
      category: 'Personal',
      appId: 'pms',
      pathSuffix: '/assigned',
    },
    {
      id: 'pms-tasks-assigned',
      title: 'pms-tasks-assigned',
      icon: User,
      category: 'Personal',
      appId: 'pms',
      pathSuffix: '/assigned',
    },
    {
      id: 'pms-tasks-today',
      title: 'pms-tasks-today',
      icon: Calendar,
      category: 'Personal',
      appId: 'pms',
      pathSuffix: '/today',
    },
  ],
  appRoutePaths: [
    getAppRoutePattern('pms.root'),
    getAppRoutePattern('pms.assigned'),
    getAppRoutePattern('pms.today'),
    getAppRoutePattern('pms.list'),
    getAppRoutePattern('pms.space'),
    getAppRoutePattern('pms.space-docs'),
    getAppRoutePattern('pms.space-doc'),
    getAppRoutePattern('pms.space-whiteboards'),
    getAppRoutePattern('pms.space-whiteboard'),
  ],
};
