import { getAppRoutePattern } from '@miy/contracts/app-routes';
import {
  AlertTriangle,
  Archive,
  CheckCircle2,
  Clock3,
  Inbox,
  ListMusic,
  Mic,
  Users,
} from 'lucide-react';

import type { AppModuleManifest } from '@miy/core-web/navigation-types';

export const recordingManifest: AppModuleManifest = {
  appBarItem: { id: 'recording', title: 'recording', icon: Mic },
  contract: {
    owner: 'recording-platform',
    permissions: [],
    apiDomain: 'recording',
    aiCapabilities: [],
    writeAuditActions: [],
    appLocalTests: [
      'packages/official-suite-web/src/recording/recorder/recording-recorder-runtime.spec.ts',
      'packages/official-suite-web/src/recording/recorder/recording-recovery-session-plan.spec.ts',
      'packages/official-suite-web/src/recording/recorder/recording-upload-session.spec.ts',
      'packages/official-suite-web/src/recording/views/RecordingDetailView.spec.tsx',
      'packages/official-suite-web/src/recording/views/recording-collection-workflow.spec.tsx',
      'packages/official-suite-web/src/recording/views/recording-detail-model.spec.ts',
      'packages/official-suite-web/src/recording/views/recording-view-model.spec.ts',
      'packages/official-suite-web/src/recording/views/useRecordingDetailController.spec.ts',
      'apps/web/src/app-modules/recording/ownership.spec.tsx',
      'apps/web/src/app/shell/official-module-ownership.spec.tsx',
      'apps/web/src/platform/apps/app-links.spec.ts',
      'scripts/recording-sync-asset.test.mjs',
      'apps/api/tests/test_recording_targets.py',
    ],
  },
  defaultActiveNavItemId: 'recording-quick',
  navItems: [
    {
      id: 'recording-quick',
      title: 'recording-quick',
      icon: Mic,
      category: 'Recordings',
      appId: 'recording',
    },
    {
      id: 'recording-mine',
      title: 'recording-mine',
      icon: ListMusic,
      category: 'Recordings',
      appId: 'recording',
      pathSuffix: '?view=mine',
    },
    {
      id: 'recording-meeting',
      title: 'recording-meeting',
      icon: Users,
      category: 'Recording Categories',
      appId: 'recording',
      pathSuffix: '?view=mine&category=meeting',
    },
    {
      id: 'recording-task',
      title: 'recording-task',
      icon: CheckCircle2,
      category: 'Recording Categories',
      appId: 'recording',
      pathSuffix: '?view=mine&category=task',
    },
    {
      id: 'recording-unlinked',
      title: 'recording-unlinked',
      icon: Inbox,
      category: 'Recording Categories',
      appId: 'recording',
      pathSuffix: '?view=mine&category=unlinked',
    },
    {
      id: 'recording-processing',
      title: 'recording-processing',
      icon: Clock3,
      category: 'Recording Status',
      appId: 'recording',
      pathSuffix: '?view=processing',
    },
    {
      id: 'recording-failed',
      title: 'recording-failed',
      icon: AlertTriangle,
      category: 'Recording Status',
      appId: 'recording',
      pathSuffix: '?view=failed',
    },
    {
      id: 'recording-archived',
      title: 'recording-archived',
      icon: Archive,
      category: 'Recording Status',
      appId: 'recording',
      pathSuffix: '?view=archived',
    },
  ],
  appRoutePaths: [
    getAppRoutePattern('recording.root'),
    getAppRoutePattern('recording.detail'),
  ],
};
